/**
 * The API's own types, from src/lib/api/schema.d.ts — generated from the backend's Swagger
 * by `npm run api:types`, and regenerated by CI, which fails on any difference. The feature
 * api files name their DTOs from here (`type BookingDto = ApiDto<'Dixels.Bookings.BookingDto'>`)
 * instead of copying them, so a field renamed, removed or retyped on the backend is a
 * TypeScript error where it's used, not a silent mismatch.
 *
 * The schema says what C# says: a property that's always present is required, and one that
 * can be null (`int?`, `string?`, a nullable DTO) is `?: T | null`.
 */
import type { components } from './schema'

type Schemas = components['schemas']

/**
 * A DTO or enum by its full server name, e.g. 'Dixels.Bookings.CreateBookingDto' — for what
 * the app sends, where a property the API marks optional may indeed be left out.
 */
export type ApiDto<Name extends keyof Schemas> = Schemas[Name]

/**
 * A DTO the API sends back. ABP writes every property, null when empty, so none is ever
 * missing: the optional marks come off (`floorNumber?: number | null` reads
 * `floorNumber: number | null`), at every depth. Nothing gains a null it didn't have.
 */
export type ApiResponse<Name extends keyof Schemas> = Present<Schemas[Name]>

type Present<T> = T extends readonly (infer U)[] ? Present<U>[] : T extends object ? { [K in keyof T]-?: Present<T[K]> } : T

/**
 * `true` when a const object (`{ Allow: 0, Warn: 1, Block: 2 }`) names exactly the values of
 * the API's enum — no stale value, none missing. Used through `Check<…>` in enumChecks.ts.
 */
export type NamesEvery<Obj, Enum> = [Obj[keyof Obj]] extends [Enum] ? ([Enum] extends [Obj[keyof Obj]] ? true : false) : false

/** Fails to compile unless `T` is `true`. */
export type Check<T extends true> = T
