// Turns the backend's English texts (the ABP resource every language is translated from)
// into a TypeScript type, so t('Nav:Hierarchy') is checked at compile time: a mistyped or
// removed key fails `tsc` instead of showing the raw key on screen. The result,
// src/i18n/keys.d.ts, is committed (the frontend's Docker build never sees the backend);
// CI regenerates it and fails on any difference.
//
// Usage: node scripts/i18n-types.mjs   (npm run i18n:types)
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const source = new URL('../../backend/src/Dixels.Domain.Shared/Localization/Dixels/en.json', import.meta.url)
const target = new URL('../src/i18n/keys.d.ts', import.meta.url)

const { texts } = JSON.parse(readFileSync(source, 'utf8'))
const keys = Object.keys(texts).sort()

const body = keys.map((key) => `  ${JSON.stringify(key)}: string`).join('\n')
const out = `// Generated by scripts/i18n-types.mjs from backend/src/Dixels.Domain.Shared/Localization/Dixels/en.json.
// Do not edit: add or change texts in that file, then run \`npm run i18n:types\`.
export interface TextKeys {
${body}
}
`

writeFileSync(target, out)
console.log(`Wrote ${keys.length} keys to ${fileURLToPath(target)}`)
