<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Dixels.SpaceOs</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dixels.SpaceOs.Domain\Dixels.SpaceOs.Domain.csproj" />
    <ProjectReference Include="..\Dixels.SpaceOs.TestBase\Dixels.SpaceOs.TestBase.csproj" />
  </ItemGroup>


</Project>
