import { readdirSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { below, BREAKPOINTS, up } from './breakpoints'

const stylesDir = fileURLToPath(new URL('../styles/', import.meta.url))

/** Every width a stylesheet may use: a breakpoint (min-width) or the pixel below it (max-width). */
const allowedWidths = new Set(Object.values(BREAKPOINTS).flatMap((px) => [px, px - 1]))

describe('breakpoints', () => {
  it('builds the same queries Tailwind prefixes use', () => {
    expect(up('md')).toBe('(min-width: 768px)')
    expect(below('md')).toBe('(max-width: 767px)')
  })

  it('are the only widths the stylesheets query', () => {
    // tokens.css is generated by shadcn and has no layout queries; everything else is ours.
    const files = readdirSync(stylesDir).filter((name) => name.endsWith('.css'))
    const offenders: string[] = []
    for (const name of files) {
      const css = readFileSync(`${stylesDir}${name}`, 'utf8')
      for (const match of css.matchAll(/@media[^{]*?\((?:min|max)-width:\s*(\d+)px\)/g)) {
        const width = Number(match[1])
        if (!allowedWidths.has(width)) offenders.push(`${name}: ${match[0].trim()}`)
      }
    }
    expect(offenders).toEqual([])
  })
})
